# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\StartWindow_widget_v4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        Form.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.DubugTlttextBrowser = QtWidgets.QTextBrowser(Form)
        self.DubugTlttextBrowser.setGeometry(QtCore.QRect(0, 0, 900, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DubugTlttextBrowser.setFont(font)
        self.DubugTlttextBrowser.setStyleSheet("background-color: rgb(60, 60, 60)")
        self.DubugTlttextBrowser.setObjectName("DubugTlttextBrowser")
        self.StartBtn = QtWidgets.QPushButton(Form)
        self.StartBtn.setGeometry(QtCore.QRect(50, 430, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.StartBtn.setFont(font)
        self.StartBtn.setObjectName("StartBtn")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(680, 520, 224, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.WindowCtrlLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.WindowCtrlLayout.setContentsMargins(0, 0, 30, 0)
        self.WindowCtrlLayout.setObjectName("WindowCtrlLayout")
        self.BackBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BackBtn.setFont(font)
        self.BackBtn.setObjectName("BackBtn")
        self.WindowCtrlLayout.addWidget(self.BackBtn)
        self.NextBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.NextBtn.setFont(font)
        self.NextBtn.setObjectName("NextBtn")
        self.WindowCtrlLayout.addWidget(self.NextBtn)
        self.DebugtextBrowser = QtWidgets.QTextBrowser(Form)
        self.DebugtextBrowser.setEnabled(True)
        self.DebugtextBrowser.setGeometry(QtCore.QRect(0, 30, 900, 380))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DebugtextBrowser.setFont(font)
        self.DebugtextBrowser.setMouseTracking(True)
        self.DebugtextBrowser.setTabletTracking(False)
        self.DebugtextBrowser.setToolTipDuration(-1)
        self.DebugtextBrowser.setStatusTip("")
        self.DebugtextBrowser.setStyleSheet("background-color: rgb(30, 30, 30)")
        self.DebugtextBrowser.setTabChangesFocus(False)
        self.DebugtextBrowser.setUndoRedoEnabled(False)
        self.DebugtextBrowser.setObjectName("DebugtextBrowser")
        self.in_uploadfileDir = QtWidgets.QLineEdit(Form)
        self.in_uploadfileDir.setGeometry(QtCore.QRect(429, 430, 441, 31))
        self.in_uploadfileDir.setObjectName("in_uploadfileDir")
        self.BrowserBtn = QtWidgets.QPushButton(Form)
        self.BrowserBtn.setGeometry(QtCore.QRect(300, 430, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BrowserBtn.setFont(font)
        self.BrowserBtn.setObjectName("BrowserBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CANFlashOTA"))
        self.DubugTlttextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; color:#909090;\">Debug</span></p></body></html>"))
        self.StartBtn.setText(_translate("Form", "Start"))
        self.BackBtn.setText(_translate("Form", "Back"))
        self.NextBtn.setText(_translate("Form", "Next"))
        self.DebugtextBrowser.setToolTip(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.DebugtextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BrowserBtn.setText(_translate("Form", "Browser"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
